<?php 
$this->title = "Mis usuarios";
$this->headTitle($this->title);
?>
<p><a href="<?php echo $this->url(array('controller'=>'users', 
 'action'=>'add'));?>">Add new user</a></p>
<table>
<tr>
 <th>Id</th>
 <th>Email</th>
 <th>Display name</th>
 <th>State</th>
 <th>User type</th>
 <th>&nbsp;</th>
</tr>
<?php foreach($this->users as $user) : ?>
<tr>
 <td><?php echo $this->escape($user->iduser);?></td>
 <td><?php echo $this->escape($user->email);?></td>
 <td><?php echo $this->escape($user->display_name);?></td>
 <td><?php echo $this->escape($user->state);?></td>
 <td><?php echo $this->escape($user->idusertype);?></td>
<td>
<a href="<?php echo $this->url(array('controller'=>'users',
'action'=>'edit', 'id'=>$user->id));?>">Edit</a>
<a href="<?php echo $this->url(array('controller'=>'users',
'action'=>'delete', 'id'=>$user->id));?>">Delete</a>
</td>
</tr>
<?php endforeach; ?>
</table>